### ISSUE TITLE
Startpage

### ISSUE THREAD

**Issue by wikimatze** [padrino/padrino-new-web#14]
Let's discuss and try out new things.

**Comment by wikimatze** [comment]
I've been working on the front-page today: 
![padrino-index-page](https://cloud.githubusercontent.com/assets/264708/5892494/1230319a-a4c1-11e4-8fa7-2c661abfa232.png). Comments are welcome.

**Comment by moonglum** [comment]
I like the logo :+1: I also like the overall design of the page! Comments:

* I think the two introductions are a little weird. "Padrino is a Ruby Framework..." is basically the first sentence of the paragraph, right?
* I would try to put the "View on GitHub" and "Latest stable" in the left sidebar beneath the logo.
* I think "Getting Started" should be a call to action with "gem install padrino". But that's probably not so much design anymore, right? :wink: 

What do you think?

**Comment by wikimatze** [comment]
View on Github moved and reworked getting started, see the attached image
![padrino-index-page_2](https://cloud.githubusercontent.com/assets/264708/5914758/c858af5c-a5fb-11e4-8d72-6ee430611d57.png)

**Comment by wikimatze** [comment]
@moonglum here another variant with only one introduction part:

![padrino-index-page_3](https://cloud.githubusercontent.com/assets/264708/5914851/054f0784-a5fd-11e4-961e-175d0182ee7b.png)

**Comment by moonglum** [comment]
@wikimatze Great :+1: I think that the "view on GitHub" and "Latest stable" are a little close together.

About the two versions: After seeing it in comparison, I would say I prefer the version with one sentence in a bigger font size :smile:

**Comment by wikimatze** [comment]
I did the changes under http://padrinorb.wikimatze.de/ and think I'm now done with the front-page.

**Comment by nesquena** [comment]
Nice, this is really coming together! Great work!

**Comment by wikimatze** [comment]
Thanks, but the great thanks goes to @angeloashmore - he had the awesome layout idea.

**Comment by moonglum** [comment]
Thanks @angeloashmore :smile:
