### ISSUE TITLE
Add faq

### ISSUE THREAD

**Issue by wikimatze** [padrino/padrino-new-web#15]
Inspiration from https://github.com/padrino/padrino-framework/blob/master/padrino-docs/pages/faq.md

**Comment by wikimatze** [comment]
I made a first draft of a possible [FAQ section](http://padrinorb.wikimatze.de/faq/). What do you think?

![padrino-faq-page](https://cloud.githubusercontent.com/assets/264708/5933513/1011fc1a-a6c2-11e4-9263-d3322639318f.png)

**Comment by moonglum** [comment]
Would there be a list of questions, and when you click on it, it would expand? I think it's a little hard to read the question and to see that it is kind-of the heading for the section. Maybe increase the font-size of the question?

**Comment by wikimatze** [comment]
What about this?

![padrino-faq-page_2](https://cloud.githubusercontent.com/assets/264708/5953314/ed72279a-a787-11e4-8fd6-7d384999d04e.png)

**Comment by moonglum** [comment]
This is definitely clearer :+1: Red is the highlight color of the page, right?

**Comment by wikimatze** [comment]
Exactly!

**Comment by wikimatze** [comment]
I'm done with this issue.
